version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: PowercutDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@localhost:5432/PowercutDB?schema=public
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=powercut-client
      - KEYCLOAK_PUBLIC_KEY=YOUR_PUBLIC_KEY_HERE
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  pgdata:
